name: RunDeploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TARGET: 'target'

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Build lambda
        run: |
          mkdir $TARGET
          mkdir $TARGET/monitoring-bot-ui
          pip install -r requirements.txt --target $TARGET/monitoring-bot-ui
          cp monitoring-bot-ui/*.py $TARGET/monitoring-bot-ui -r
          cd $TARGET/monitoring-bot-ui
          zip -r ../../monitoring-bot-ui.zip .
          cd ../..
      - name: Deploy lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: ${{ secrets.MASTER_LAMBDA_NAME }}
          zip_file: monitoring-bot-ui.zip